# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111213)
$foreground = rgb(F3E3DB)
$color0 = rgb(393A3B)
$color1 = rgb(444A52)
$color2 = rgb(733E44)
$color3 = rgb(A4464B)
$color4 = rgb(5B6784)
$color5 = rgb(856587)
$color6 = rgb(A68373)
$color7 = rgb(E6CFC3)
$color8 = rgb(A19189)
$color9 = rgb(5B636D)
$color10 = rgb(9A525A)
$color11 = rgb(DA5E64)
$color12 = rgb(798AB0)
$color13 = rgb(B186B4)
$color14 = rgb(DDAF99)
$color15 = rgb(E6CFC3)
