# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Warp cursor to center of Acer monitor (4K @ 1.25 scale, logical pos 2560,0, size 3072x1728) on startup
exec-once = sleep 1 && hyprctl dispatch movecursor 4096 864
